# Default values for snakemake runtime arguments
# Maximum number of jobs to submit concurrently
jobs: 100
# Number of cores used by local snakemake rules
local-cores: 1
# Maximum number of jobs to submit per second
max-jobs-per-second: 5
# Maximum number of job status checks per second
max-status-checks-per-second: 10
# Cluster submission script


executor: cluster-generic
#default_resources: []
cluster-generic-submit-cmd: "submit.py"
cluster-generic-status-cmd: "status.py"



#cluster: "submit.py"
# Cluster job status script
#cluster-status: "status.py"
# Number of times Snakemake tries to restart a failed job
restart-times: 0
